name: Check that version is updated

on:
  pull_request:
    branches: [ master ]

jobs:
  CheckVersion:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch repo
        run: git fetch

      - name: Version check for python package
        id: check_sdk_version
        run: |
          if [ -z $(git diff origin/master HEAD -- requirements.txt | grep lucidtech-las)]
          then
            echo "::set-output name=updated_sdk_version::0"
          else
            echo "::set-output name=updated_sdk_version::1"
          fi

      - name: comment PR
        if: steps.check_sdk_version.outputs.updated_sdk_version == 0
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ":warning: You should probably update version number for the lucidtech-las pip package in requirements.txt"
          check_for_duplicate_msg: true
