name: Check that version is updated

on:
  pull_request:
    branches: [ master ]

jobs:
  CheckVersion:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch repo
        run: git fetch

      - name: Version check
        run: |
          if [ -z $(git diff origin/master HEAD -- setup.py | grep version )]
          then
            echo "You should probably update version number"
            exit 1
          fi

      - name: Version check for python package
        run: |
          if [ -z $(git diff origin/master HEAD -- requirements.txt | grep lucidtech-las)]
          then
            echo "You should probably update version number for the lucidtech-las pip package in requirements.txt"
            exit 1
          fi
